# Generated by Django 3.1.7 on 2021-04-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdapp', '0002_remove_userprofileinfo_subject_taught'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='subject_taught',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
